// ielts/dto/enums.ts

export enum ExamType {
    READING_ONLY = 'READING_ONLY',
    SPEAKING_ONLY = 'SPEAKING_ONLY',
    WRITING_ONLY = 'WRITING_ONLY',
    LISTENING_ONLY = 'LISTENING_ONLY',

    READING_SPEAKING = 'READING_SPEAKING',
    READING_WRITING = 'READING_WRITING',
    READING_LISTENING = 'READING_LISTENING',
    SPEAKING_WRITING = 'SPEAKING_WRITING',
    SPEAKING_LISTENING = 'SPEAKING_LISTENING',
    WRITING_LISTENING = 'WRITING_LISTENING',

    READING_SPEAKING_WRITING = 'READING_SPEAKING_WRITING',
    READING_SPEAKING_LISTENING = 'READING_SPEAKING_LISTENING',
    READING_WRITING_LISTENING = 'READING_WRITING_LISTENING',
    SPEAKING_WRITING_LISTENING = 'SPEAKING_WRITING_LISTENING',

    FULL_MOCK_TEST = 'FULL_MOCK_TEST',
}

export enum ExamModule {
    ACADEMIC = 'ACADEMIC',
    GENERAL = 'GENERAL',
}

export enum DifficultyLevel {
    BAND_4_5 = 'BAND_4_5',
    BAND_5_6 = 'BAND_5_6',
    BAND_6_7 = 'BAND_6_7',
    BAND_7_8 = 'BAND_7_8',
    BAND_8_9 = 'BAND_8_9',
}

export enum SpeakingPartType {
    INTRODUCTION_FAMILIAR_TOPICS = 'INTRODUCTION_FAMILIAR_TOPICS',
    LONG_TURN_CUE_CARD = 'LONG_TURN_CUE_CARD',
    ANALYTICAL_DISCUSSION = 'ANALYTICAL_DISCUSSION',
}

export enum WritingTaskSubtype {
    // Academic Task 1
    LINE_GRAPH = 'LINE_GRAPH',
    BAR_CHART = 'BAR_CHART',
    PIE_CHART = 'PIE_CHART',
    TABLE = 'TABLE',
    MAP = 'MAP',
    PROCESS_DIAGRAM = 'PROCESS_DIAGRAM',
    MIXED_CHARTS = 'MIXED_CHARTS',
    // General Task 1
    FORMAL_LETTER = 'FORMAL_LETTER',
    SEMI_FORMAL_LETTER = 'SEMI_FORMAL_LETTER',
    PERSONAL_LETTER = 'PERSONAL_LETTER',
    // Task 2
    OPINION_ESSAY = 'OPINION_ESSAY',
    DISCUSSION_ESSAY = 'DISCUSSION_ESSAY',
    ADVANTAGE_DISADVANTAGE_ESSAY = 'ADVANTAGE_DISADVANTAGE_ESSAY',
    PROBLEM_SOLUTION_ESSAY = 'PROBLEM_SOLUTION_ESSAY',
    TWO_PART_QUESTION_ESSAY = 'TWO_PART_QUESTION_ESSAY',
}

export enum QuestionType {
    // Reading & Listening — shared
    MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
    MULTIPLE_CHOICE_MULTIPLE_ANSWERS = 'MULTIPLE_CHOICE_MULTIPLE_ANSWERS',
    SENTENCE_COMPLETION = 'SENTENCE_COMPLETION',
    SUMMARY_COMPLETION = 'SUMMARY_COMPLETION',
    NOTE_COMPLETION = 'NOTE_COMPLETION',
    TABLE_COMPLETION = 'TABLE_COMPLETION',
    FLOW_CHART_COMPLETION = 'FLOW_CHART_COMPLETION',
    FORM_COMPLETION = 'FORM_COMPLETION',

    // Listening specific
    MATCHING = 'MATCHING',
    PLAN_MAP_DIAGRAM_LABELLING = 'PLAN_MAP_DIAGRAM_LABELLING',

    // Reading specific
    MATCHING_HEADINGS = 'MATCHING_HEADINGS',
    MATCHING_INFORMATION = 'MATCHING_INFORMATION',
    MATCHING_FEATURES = 'MATCHING_FEATURES',
    MATCHING_SENTENCE_ENDINGS = 'MATCHING_SENTENCE_ENDINGS',
    TRUE_FALSE_NOT_GIVEN = 'TRUE_FALSE_NOT_GIVEN',
    YES_NO_NOT_GIVEN = 'YES_NO_NOT_GIVEN',
    SHORT_ANSWER = 'SHORT_ANSWER',

    // Writing
    TASK_1_ACADEMIC = 'TASK_1_ACADEMIC',
    TASK_1_GENERAL = 'TASK_1_GENERAL',
    TASK_2_ESSAY = 'TASK_2_ESSAY',

    // Speaking
    SPEAKING_PART_1 = 'SPEAKING_PART_1',
    SPEAKING_PART_2 = 'SPEAKING_PART_2',
    SPEAKING_PART_3 = 'SPEAKING_PART_3',
}
